// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrivateClinic.Models;

public partial class Equipment
{
    public int Id { get; set; }

    public string TypeOfEquipment { get; set; }

    public string CleaningCycle { get; set; }

    public string Maintenance { get; set; }
}