// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrivateClinic.Models;

public partial class Equipment
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Status { get; set; }

    public DateOnly? CleaningTime { get; set; }

    public string Maintenance { get; set; }
}