// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrivateClinic.Models;

public partial class MedicineStorage
{
    public int Id { get; set; }

    public string Name { get; set; }

    public double? Available { get; set; }

    public double? Total { get; set; }

    public DateOnly? ExpiredDate { get; set; }

    public virtual ICollection<MedicalRecordMedicine> MedicalRecordMedicines { get; set; } = new List<MedicalRecordMedicine>();
}