// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrivateClinic.Models;

public partial class MedicineStorage
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string TypeOfMedicine { get; set; }

    public int? Quantity { get; set; }

    public DateTime? ImportDate { get; set; }

    public DateTime? ExpiredDate { get; set; }

    public string Status { get; set; }

    public int PriceId { get; set; }

    public virtual ICollection<MedicineOrder> MedicineOrders { get; set; } = new List<MedicineOrder>();

    public virtual ICollection<Prescription> Prescriptions { get; set; } = new List<Prescription>();

    public virtual PriceList Price { get; set; }
}