// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrivateClinic.Models;

public partial class MedicineOrder
{
    public int Id { get; set; }

    public int? Quantity { get; set; }

    public int MedicineId { get; set; }

    public int OrderDetailsId { get; set; }

    public virtual MedicineStorage Medicine { get; set; }

    public virtual OrderDetail OrderDetails { get; set; }
}