// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrivateClinic.Models;

public partial class Order
{
    public int Id { get; set; }

    public string Context { get; set; }

    public long? Total { get; set; }

    public DateTime? Date { get; set; }

    public string Method { get; set; }

    public string Status { get; set; }

    public int OrderDetailsId { get; set; }

    public int CustomerId { get; set; }

    public virtual User Customer { get; set; }

    public virtual OrderDetail OrderDetails { get; set; }
}