// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrivateClinic.Models;

public partial class OrderDetail
{
    public int Id { get; set; }

    public string Description { get; set; }

    public string TypeOfOrder { get; set; }

    public virtual ICollection<MedicineOrder> MedicineOrders { get; set; } = new List<MedicineOrder>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<TreatmentOrder> TreatmentOrders { get; set; } = new List<TreatmentOrder>();
}