// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrivateClinic.Models;

public partial class PriceList
{
    public int Id { get; set; }

    public string Name { get; set; }

    public long? Price { get; set; }

    public DateOnly? UpdateDate { get; set; }

    public virtual ICollection<MedicineStorage> MedicineStorages { get; set; } = new List<MedicineStorage>();

    public virtual ICollection<Treatment> Treatments { get; set; } = new List<Treatment>();
}