// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PrivateClinic.Models;

public partial class PrivateClinicManagementDBContext : DbContext
{
    public PrivateClinicManagementDBContext(DbContextOptions<PrivateClinicManagementDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Checkup> Checkups { get; set; }

    public virtual DbSet<Equipment> Equipment { get; set; }

    public virtual DbSet<ExaminitionAppointment> ExaminitionAppointments { get; set; }

    public virtual DbSet<MedicalRecord> MedicalRecords { get; set; }

    public virtual DbSet<MedicalRecordMedicine> MedicalRecordMedicines { get; set; }

    public virtual DbSet<MedicineStorage> MedicineStorages { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Treatment> Treatments { get; set; }

    public virtual DbSet<TreatmentDetail> TreatmentDetails { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Checkup>(entity =>
        {
            entity.ToTable("CHECKUP");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.DoctorId).HasColumnName("doctorId");
            entity.Property(e => e.EndTime)
                .HasPrecision(0)
                .HasColumnName("endTime");
            entity.Property(e => e.Name)
                .HasMaxLength(40)
                .HasColumnName("name");
            entity.Property(e => e.Phone)
                .HasMaxLength(10)
                .HasColumnName("phone");
            entity.Property(e => e.Room)
                .HasMaxLength(10)
                .HasColumnName("room");
            entity.Property(e => e.StartTime)
                .HasPrecision(0)
                .HasColumnName("startTime");
            entity.Property(e => e.TreatmentId).HasColumnName("treatmentId");

            entity.HasOne(d => d.Doctor).WithMany(p => p.Checkups)
                .HasForeignKey(d => d.DoctorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CHECKUP_USER");

            entity.HasOne(d => d.Treatment).WithMany(p => p.Checkups)
                .HasForeignKey(d => d.TreatmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CHECKUP_TREATMENT");
        });

        modelBuilder.Entity<Equipment>(entity =>
        {
            entity.ToTable("EQUIPMENT");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CleaningTime).HasColumnName("cleaningTime");
            entity.Property(e => e.Maintenance)
                .HasMaxLength(40)
                .HasColumnName("maintenance");
            entity.Property(e => e.Name)
                .HasMaxLength(40)
                .HasColumnName("name");
            entity.Property(e => e.Status)
                .HasMaxLength(40)
                .HasColumnName("status");
        });

        modelBuilder.Entity<ExaminitionAppointment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_EXAMINITION APPOINTMENT");

            entity.ToTable("EXAMINITION_APPOINTMENT");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Condition)
                .HasMaxLength(40)
                .HasColumnName("condition");
            entity.Property(e => e.CustomerId).HasColumnName("customerId");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.DoctorId).HasColumnName("doctorId");
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .HasColumnName("email");
            entity.Property(e => e.Name)
                .HasMaxLength(40)
                .HasColumnName("name");
            entity.Property(e => e.Phone)
                .HasMaxLength(10)
                .HasColumnName("phone");
            entity.Property(e => e.Status)
                .HasMaxLength(40)
                .HasColumnName("status");
            entity.Property(e => e.TreatmentId).HasColumnName("treatmentId");

            entity.HasOne(d => d.Customer).WithMany(p => p.ExaminitionAppointmentCustomers)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EXAMINITION_APPOINTMENT_USER1");

            entity.HasOne(d => d.Doctor).WithMany(p => p.ExaminitionAppointmentDoctors)
                .HasForeignKey(d => d.DoctorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EXAMINITION_APPOINTMENT_USER");

            entity.HasOne(d => d.Treatment).WithMany(p => p.ExaminitionAppointments)
                .HasForeignKey(d => d.TreatmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EXAMINITION_APPOINTMENT_TREATMENT");
        });

        modelBuilder.Entity<MedicalRecord>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_MEDICAL RECORD");

            entity.ToTable("MEDICAL_RECORD");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CustomerId).HasColumnName("customerId");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasColumnName("description");
            entity.Property(e => e.RecordDate).HasColumnName("recordDate");

            entity.HasOne(d => d.Customer).WithMany(p => p.MedicalRecords)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MEDICAL_RECORD_USER");
        });

        modelBuilder.Entity<MedicalRecordMedicine>(entity =>
        {
            entity.HasKey(e => new { e.RecordId, e.MedicineId }).HasName("PK__MEDICAL___238CFF002E8A47B3");

            entity.ToTable("MEDICAL_RECORD_MEDICINES");

            entity.Property(e => e.RecordId).HasColumnName("recordId");
            entity.Property(e => e.MedicineId).HasColumnName("medicineId");
            entity.Property(e => e.Quantity).HasColumnName("quantity");

            entity.HasOne(d => d.Medicine).WithMany(p => p.MedicalRecordMedicines)
                .HasForeignKey(d => d.MedicineId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MEDICAL_R__medic__2EA5EC27");

            entity.HasOne(d => d.Record).WithMany(p => p.MedicalRecordMedicines)
                .HasForeignKey(d => d.RecordId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MEDICAL_R__recor__2DB1C7EE");
        });

        modelBuilder.Entity<MedicineStorage>(entity =>
        {
            entity.ToTable("MEDICINE_STORAGE");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Available).HasColumnName("available");
            entity.Property(e => e.ExpiredDate).HasColumnName("expiredDate");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.Total).HasColumnName("total");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.ToTable("ORDER");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CustomerEmail)
                .HasMaxLength(50)
                .HasColumnName("customerEmail");
            entity.Property(e => e.CustomerName)
                .HasMaxLength(40)
                .HasColumnName("customerName");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.Method)
                .HasMaxLength(30)
                .HasColumnName("method");
            entity.Property(e => e.Status)
                .HasMaxLength(30)
                .HasColumnName("status");
            entity.Property(e => e.Total).HasColumnName("total");
            entity.Property(e => e.TreatmentId).HasColumnName("treatmentId");

            entity.HasOne(d => d.Treatment).WithMany(p => p.Orders)
                .HasForeignKey(d => d.TreatmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ORDER_TREATMENT");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.ToTable("ROLE");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.RoleType)
                .HasMaxLength(30)
                .HasColumnName("roleType");
        });

        modelBuilder.Entity<Treatment>(entity =>
        {
            entity.ToTable("TREATMENT");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Image).HasColumnName("image");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.Price).HasColumnName("price");
            entity.Property(e => e.Session).HasColumnName("session");
        });

        modelBuilder.Entity<TreatmentDetail>(entity =>
        {
            entity.ToTable("TREATMENT_DETAIL");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Details)
                .HasMaxLength(1000)
                .HasColumnName("details");
            entity.Property(e => e.TreatmentId).HasColumnName("treatmentId");

            entity.HasOne(d => d.Treatment).WithMany(p => p.TreatmentDetails)
                .HasForeignKey(d => d.TreatmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TREATMENT_DETAIL_TREATMENT");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("USER");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address)
                .HasMaxLength(50)
                .HasColumnName("address");
            entity.Property(e => e.Age).HasColumnName("age");
            entity.Property(e => e.Email)
                .HasMaxLength(30)
                .HasColumnName("email");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.Password)
                .HasMaxLength(30)
                .HasColumnName("password");
            entity.Property(e => e.Phone)
                .HasMaxLength(10)
                .HasColumnName("phone");
            entity.Property(e => e.RoleId).HasColumnName("roleId");
            entity.Property(e => e.Username)
                .HasMaxLength(50)
                .HasColumnName("username");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_USER_ROLE");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}