// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrivateClinic.Models;

public partial class TreatmentDetail
{
    public int Id { get; set; }

    public string Details { get; set; }

    public int TreatmentId { get; set; }

    public virtual Treatment Treatment { get; set; }
}