// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrivateClinic.Models;

public partial class TreatmentOrder
{
    public int Id { get; set; }

    public int? Quantity { get; set; }

    public int TreatmentId { get; set; }

    public int OrderDetailsId { get; set; }

    public virtual OrderDetail OrderDetails { get; set; }

    public virtual Treatment Treatment { get; set; }
}